chore: add compliance checks (#71)
* chore: add compliance checks

* Update azure-pipelines.compliance.yml

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -3,39 +3,45 @@
 pr: none
 trigger: none
 
-pool: '1ES-Host-Ubuntu'
-
 workspace:
   clean: all
 
-steps:
-  # For multiline scripts, we want the whole task to fail if any line of the script fails.
-  # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
-  # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
-  # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
-  # errexit:errtrace for better error behavior.
-  - script: |
-      echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
-    displayName: Force exit on error (bash)
+jobs:
+  - template: ./azure-pipelines.compliance.yml
+    parameters:
+      serviceTreeID: 6F8CD842-E117-412F-BAE4-56A3B6166594
 
-  - task: NodeTool@0
-    inputs:
-      versionSpec: '14.x'
-      checkLatest: true
-    displayName: 'Install Node.js'
+  - job: Release
+    dependsOn: Compliance
+    pool: '1ES-Host-Ubuntu'
+    steps:
+      # For multiline scripts, we want the whole task to fail if any line of the script fails.
+      # ADO doesn't have bash configured this way by default. To fix we override the SHELLOPTS built-in variable.
+      # https://www.gnu.org/software/bash/manual/html_node/The-Set-Builtin.html
+      # The options below include ADO defaults (braceexpand:hashall:interactive-comments) plus
+      # errexit:errtrace for better error behavior.
+      - script: |
+          echo "##vso[task.setvariable variable=shellopts]braceexpand:hashall:interactive-comments:errexit:errtrace"
+        displayName: Force exit on error (bash)
 
-  - script: yarn install --frozen-lockfile
-    displayName: Install dependencies
+      - task: NodeTool@0
+        inputs:
+          versionSpec: '14.x'
+          checkLatest: true
+        displayName: 'Install Node.js'
 
-  - script: |
-      git config user.name "Fluent UI Build"
-      git config user.email "fluentui-internal@service.microsoft.com"
-      git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/griffel.git
-    displayName: Authenticate git for pushes
+      - script: yarn install --frozen-lockfile
+        displayName: Install dependencies
 
-  - script: |
-      yarn beachball publish -b origin/main --access public -y -n $(npmTokenTmp)
-      git reset --hard origin/main
-    env:
-      GITHUB_PAT: $(githubPAT)
-    displayName: Publish to NPM & bump versions
+      - script: |
+          git config user.name "Fluent UI Build"
+          git config user.email "fluentui-internal@service.microsoft.com"
+          git remote set-url origin https://$(githubUser):$(githubPAT)@github.com/microsoft/griffel.git
+        displayName: Authenticate git for pushes
+
+      - script: |
+          yarn beachball publish -b origin/main --access public -y -n $(npmTokenTmp)
+          git reset --hard origin/main
+        env:
+          GITHUB_PAT: $(githubPAT)
+        displayName: Publish to NPM & bump versions
